// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnAs0ffIrrUIiszTGz4EzwTiy2_ZRT7GA',
    appId: '1:972196611074:web:f83a65cbbaa26a84ae131b',
    messagingSenderId: '972196611074',
    projectId: 'simple-chat-apps-bb925',
    authDomain: 'simple-chat-apps-bb925.firebaseapp.com',
    storageBucket: 'simple-chat-apps-bb925.firebasestorage.app',
    measurementId: 'G-LBPD9JW4KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxk0IJO2KXaFNtX29iSer7XmZ3L7LO1tQ',
    appId: '1:972196611074:android:b24fa368b7e17618ae131b',
    messagingSenderId: '972196611074',
    projectId: 'simple-chat-apps-bb925',
    storageBucket: 'simple-chat-apps-bb925.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAFnK3ti5DLdTwzKnPiGVNtvSiFDcH4bg',
    appId: '1:972196611074:ios:cc7c80079c7e0db2ae131b',
    messagingSenderId: '972196611074',
    projectId: 'simple-chat-apps-bb925',
    storageBucket: 'simple-chat-apps-bb925.firebasestorage.app',
    iosBundleId: 'com.karismaacademy.chat',
  );
}
